### ISSUE TITLE
How do we get started writing our own project/code?

### ISSUE THREAD

**Issue by CingKong** [Lumak/Urho3D-Android-Project#1]

**Comment by Lumak** [comment]
For a question like this, you should post it on the Urho3D forum so you can get more opinions from different people.  But I'll answer it this time.

Game is just a large collection of small samples. That is: you have input to control something, UI to prompt or navigate through different levels, character sample, physics sample, etc.  All you have to do is decide **what type** of game you want to make and then gather various samples as resource to put together into a game.

**Comment by CingKong** [comment]
My bad didn't ask clearly.

My question is how do we actually put our own code in this android studio project, can we write C++ code?
Im confused cuz i went through google and all related articles/posts i got are only about the building urho3d part, nobody talks about writing something and link with the urho3d lib. 

And the source code in the android studio project is even more confusing, there are not actually codes demonstrating how to use urho3d in android project except loading scripts?

**Comment by CingKong** [comment]
Then ppl will need to launch the actual App from the sample launcher like we do. 
This doesn't make points. xD

**Comment by Lumak** [comment]
You don't understand the process and you refuse to follow instructions. 
Closing this.
